"""Add UserSettings.show_assistant_messages.

Revision ID: 3286a7588f5c
Revises: a740e029fe84
Create Date: 2023-09-14 23:25:24.841670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3286a7588f5c'
down_revision = 'a740e029fe84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_assistant_messages', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('show_assistant_messages')

    # ### end Alembic commands ###
