"""empty message

Revision ID: 4ae085cc16bb
Revises: 6d14c4108729
Create Date: 2023-12-26 23:17:55.131330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae085cc16bb'
down_revision = '6d14c4108729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_stytch_user_id'), ['stytch_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_stytch_user_id'))

    # ### end Alembic commands ###
