"""Added ChatMessage.role and ChatMessage.model_name

Revision ID: 9fcad92c2b7b
Revises: 0e17aedf7a42
Create Date: 2023-09-11 22:41:52.313852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fcad92c2b7b'
down_revision = '0e17aedf7a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=False, server_default='user'))
        batch_op.add_column(sa.Column('model_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_column('model_name')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
